[tox]
envlist =
    coverage-erase-{py39,py310,py311}
    test-{py39,py310,py311}-django{42,50,51}
    coverage-report-{py39,py310,py311}
    flake8-{py39,py310,py311}
skip_missing_interpreters = True

[testenv]
usedevelop = True
deps =
    django42: Django>=4.2,<5.0
    django50: Django>=5.0,<5.1
    django51: Django>=5.1,<5.2
    coverage>=4.1
    mutpy>=0.5.1
commands =
    coverage-erase: coverage erase
    test: coverage run tests/manage.py test test_project
    coverage-report: coverage report

[testenv:flake8]
basepython = python3.11
deps =
    flake8>=2.5.4
    flake8-blind-except>=0.1.1
    flake8-docstrings>=1.0.2
    flake8-isort>=2.0.1
    flake8-quotes>=0.8.1
    pydocstyle>=1.1.1
    isort>=4.2.5
    pep8-naming>=0.4.1
    flake8-debugger>=1.4.0
commands =
    isort --check-only django_mutpy tests
    flake8

[flake8]
max-line-length=120
exclude=venv,migrations,.tox
inline-quotes=single
avoid-escape=true
